/* eslint-disable @next/next/no-img-element -- Local artwork with fixed aspect ratios. */
import type {CSSProperties} from 'react';
import c from '../content.json';
export function Tile({kind=0,label,note,index=0}:{kind?:number;label?:string;note?:string;index?:number}){const x=[4.1,34.9,65.7,96.5][kind%4];const y=[12.32,49.28,86.24][Math.floor(kind/4)];return <div className={`illustrated-node tile-kind-${kind}`} style={{'--i':index} as CSSProperties}><span className="tile-wrap"><span className="tile-art" aria-hidden="true" style={{backgroundPosition:`${x}% ${y}%`}}/>{kind===1&&<span className="checks-mask" aria-hidden="true">{[0,1,2].map(i=><svg key={i} viewBox="0 0 20 20" style={{'--check':i} as CSSProperties}><path pathLength="1" d="m3 10 5 5L17 3"/></svg>)}</span>}{kind===4&&<span className="complete-mask" aria-hidden="true"><svg viewBox="0 0 100 100"><path pathLength="1" d="m20 50 22 23L82 22"/></svg></span>}{kind===2&&<span className="calendar-dates" aria-hidden="true">{[0,1,2].map(i=><i key={i} style={{'--check':i} as CSSProperties}/>)}</span>}</span>{label&&<strong>{label}</strong>}{note&&<small>{note}</small>}</div>;}
export function Route({d,viewBox='0 0 1000 600',className=''}:{d:string;viewBox?:string;className?:string}){return <svg className={`ink-route ${className}`} viewBox={viewBox} preserveAspectRatio={viewBox==='0 0 1672 941'?'xMidYMid meet':'none'} aria-hidden="true"><path className="route-base" d={d}/><path className="route-draw" pathLength="1" d={d}/><circle className="route-lead" r="5" style={{offsetPath:`path('${d}')`}}/></svg>;}
export function Workflow({labels=false}:{labels?:boolean}){return <div className="ordered-workflow"><Route d="M90 180 H910" viewBox="0 0 1000 220"/>{[0,1,2,3,4].map((kind,i)=><div className={`ordered-item action-${kind}`} style={{'--i':i} as CSSProperties} key={kind}><Tile kind={kind} index={i} label={labels?['People','Tasks','Schedule','Updates','Complete'][i]:undefined}/><span className="node-stem"/><span className="node-seal" aria-hidden="true"><svg viewBox="0 0 30 30"><circle cx="15" cy="15" r="11"/><path d={i===4?'m9 15 4 4 8-9':'M10 15h10M15 10v10'}/></svg></span></div>)}</div>;}
export function Opportunity(){return <div className="opportunity-art"><div className="drafting-fragments" aria-hidden="true"/><Route d="M430 310H475Q510 310 510 155H930 M475 310Q510 310 510 475H945"/><div className="opportunity-input"><Workflow/></div><div className="opportunity-row operations">{[5,6,7].map((k,i)=><div className={`benefit benefit-${k}`} key={k} style={{'--i':i+5} as CSSProperties}>{k===6&&<div className="separate-people" aria-hidden="true">{[0,1,2].map(j=><Tile kind={0} key={j}/>)}</div>}<Tile kind={k} label={['Time saved','Better coordination','Greater accuracy'][i]} index={i+5}/></div>)}</div><div className="opportunity-row growth">
 <div className="benefit benefit-speaker" style={{'--i':8} as CSSProperties}><Tile kind={8} label="More exposure"/><svg className="sound-lines" viewBox="0 0 100 100" aria-hidden="true"><path d="m80 25 12-8m-10 24 15-1m-17 17 12 8"/></svg></div>
 <div className="benefit benefit-growth" style={{'--i':9} as CSSProperties}><Tile kind={9} label="Marketing aligned"/><svg className="growth-arrow" viewBox="0 0 100 100" aria-hidden="true"><path pathLength="1" d="m15 55 20-20 17 13 30-30m-15 0h15v15"/></svg></div>
 <div className="benefit benefit-leads" style={{'--i':10} as CSSProperties}><div className="lead-people" aria-hidden="true">{[0,1,2].map(j=><Tile kind={0} key={j}/>)}</div><div className="paper-email"><span className="mail-subject">New leads</span><span>1. Alex Morgan</span><span>2. Jamie Taylor</span><span>3. Sam Rivera</span></div><strong>Leads captured</strong></div>
 <div className="benefit benefit-followup" style={{'--i':11} as CSSProperties}><div className="paper-email"><span className="mail-subject">Follow-up</span><span className="scheduled">Scheduled</span><span className="sent">Sent ✓</span><svg viewBox="0 0 100 55" aria-hidden="true"><path d="M6 6h88v43H6Zm0 0 44 28L94 6"/></svg></div><strong>Follow-up automated</strong></div>
 </div></div>;}
export function Invoice(){return <span className="illustrated-node"><span className="tile-wrap invoice-tile" aria-hidden="true"><svg viewBox="0 0 40 40"><path d="M10 5h15l6 6v24H10Z M25 5v6h6"/><path d="M14 16h13M14 21h13M14 26h8"/><rect x="22" y="29" width="9" height="5"/><path d="M26.5 30v3M25.5 30.5h1.5a.8.8 0 0 1 0 1.5h-1a.8.8 0 0 0 0 1.5h1.5" className="invoice-sign"/></svg></span></span>;}
export function Pressure(){return <div className="pressure-art"><img className="pressure-owner" src="/images/owner-pressure.jpg" width="1536" height="1024" loading="lazy" alt="Business owner at a desk, interrupted by competing tasks."/>{c.pressure.objects.map(([title,note],i)=><div className={`interruption interruption-${i}`} key={i}>{i===1||i===2?<Invoice/>:i===7?<svg className="whatsapp-icon" viewBox="0 0 32 32" aria-label="WhatsApp"><path d="M16 3A12 12 0 0 0 6 22L4 29l7-2A12 12 0 1 0 16 3Z" fill="#386f65"/><path d="M11 9c-4 3 4 13 9 13l2-4-4-2-2 2c-2-1-4-3-4-5l2-1Z" fill="#f4e6ce"/></svg>:<Tile kind={[3,1,1,0,2,0,0][i]}/>}<div><strong>{title}</strong><small>{note}</small></div><i/></div>)}</div>;}
export function Transformation(){return <div className="transformation-art"><img src="/images/transformation-source.jpg" width="1672" height="941" loading="lazy" alt="Layered manual papers converge through a human decision into an orderly sequence of tasks, dates, messages and completion."/><Route viewBox="0 0 1672 941" d="M430 280 C650 280 690 550 1005 550 M410 480 C660 480 770 550 1005 550 M390 730 C720 730 720 550 1005 550"/><div className="human-caption">Human judgment stays at the center.</div></div>;}
