/* eslint-disable @next/next/no-img-element -- Local artwork with fixed aspect ratios. */
import type {CSSProperties,ReactNode} from 'react';
import c from '../content.json';
const tileParts:Record<number,string[]>={1:["draw1-base","draw1-v0","draw1-v1","draw1-v2"],3:["draw3-body","draw3-flap"],4:["draw4-ring","draw4-v"],8:["draw8-base","draw8-l0","draw8-l1","draw8-l2"],9:["draw9-base","draw9-arrow"]};
/* Layered paper tiles: paper cutout + drawing cutouts extracted from the approved paper-objects sheet (see public/images/PROVENANCE.md). */
export function Tile({kind=0,label,note,index=0,children}:{kind?:number;label?:string;note?:string;index?:number;children?:ReactNode}){const layers=tileParts[kind]??["draw"+kind];return <div className={`illustrated-node tile-kind-${kind}`} style={{"--i":index} as CSSProperties}><span className="tile-wrap" aria-hidden="true"><img className="tile-paper" src={`/images/tiles/paper${kind}.png`} width="280" height="280" alt="" loading="lazy"/>{kind===3&&<span className="tile-pocket"><img className="tile-letter" src="/images/tiles/draw1.png" width="280" height="280" alt="" loading="lazy"/></span>}{layers.map(l=><img key={l} className={`tile-draw ${l}`} src={`/images/tiles/${l}.png`} width="280" height="280" alt="" loading="lazy"/>)}{children}{kind===2&&<svg className="calendar-marks" viewBox="0 0 280 280">{[[155,129],[90,159],[187,189]].map(([x,y],i)=><path key={i} pathLength="1" style={{"--check":i} as CSSProperties} d={`M${x-15} ${y-2}c1-11 12-15 20-12s13 12 8 20-16 9-22 4-9-9-6-14`}/>)}</svg>}</span>{label&&<strong>{label}</strong>}{note&&<small>{note}</small>}</div>;}
export function Route({d,viewBox='0 0 1000 600',className='',fit}:{d:string;viewBox?:string;className?:string;fit?:string}){return <svg className={`ink-route ${className}`} viewBox={viewBox} preserveAspectRatio={fit??(viewBox==='0 0 1672 941'?'xMidYMid meet':'none')} aria-hidden="true"><path className="route-base" d={d}/><path className="route-draw" pathLength="1" d={d}/><circle className="route-lead" r="5" style={{offsetPath:`path('${d}')`}}/></svg>;}
export function Workflow({labels=false}:{labels?:boolean}){return <div className="ordered-workflow"><Route d="M90 16 H910" viewBox="0 0 1000 32"/>{[0,1,2,3,4].map((kind,i)=><div className={`ordered-item action-${kind}`} style={{'--i':i} as CSSProperties} key={kind}><Tile kind={kind} index={i} label={labels?['People','Tasks','Schedule','Updates','Complete'][i]:undefined}/><span className="node-stem"/><span className="node-seal" aria-hidden="true"><svg viewBox="0 0 30 30"><circle cx="15" cy="15" r="11"/><path d={i===4?'m9 15 4 4 8-9':'M10 15h10M15 10v10'}/></svg></span></div>)}</div>;}
export function Opportunity(){return <div className="opportunity-art"><div className="drafting-fragments" aria-hidden="true"/><Route className="branch-top" d="M392 399 H462 C525 399 505 189 585 189 H984"/><Route className="branch-bottom" d="M392 399 H462 C510 399 485 453 545 453 H984"/><div className="opportunity-input"><Workflow/></div><div className="opportunity-row operations">{[5,6,7].map((k,i)=><div className={`benefit benefit-${k}`} key={k} style={{'--i':i+5} as CSSProperties}>{k===6&&<div className="separate-people" aria-hidden="true">{[0,1,2].map(j=><Tile kind={0} key={j}/>)}</div>}<Tile kind={k} label={['Time saved','Better coordination','Greater accuracy'][i]} index={i+5}/></div>)}</div><div className="opportunity-row growth">
 <div className="benefit benefit-speaker" style={{'--i':8} as CSSProperties}><Tile kind={8} label="Exposure"/></div>
 <div className="benefit benefit-growth" style={{'--i':9} as CSSProperties}><Tile kind={9} label="Marketing"/></div>
 <div className="benefit benefit-leads" style={{'--i':10} as CSSProperties}><div className="lead-people" aria-hidden="true">{[0,1,2].map(j=><Tile kind={0} key={j}/>)}</div><Tile kind={1} label="Leads captured"/></div>
 <div className="benefit benefit-followup" style={{'--i':11} as CSSProperties}><Tile kind={3} label="Follow-up automated"><span className="followup-badge"><img className="badge-clock" src="/images/tiles/draw5.png" width="280" height="280" alt="" loading="lazy"/><img className="badge-check" src="/images/tiles/draw4-v.png" width="280" height="280" alt="" loading="lazy"/></span></Tile></div>
 </div></div>;}
export function Invoice(){return <span className="illustrated-node"><span className="tile-wrap invoice-tile" aria-hidden="true"><svg viewBox="0 0 40 40"><path d="M10 5h15l6 6v24H10Z M25 5v6h6"/><path d="M14 16h13M14 21h13M14 26h8"/><rect x="22" y="29" width="9" height="5"/><path d="M26.5 30v3M25.5 30.5h1.5a.8.8 0 0 1 0 1.5h-1a.8.8 0 0 0 0 1.5h1.5" className="invoice-sign"/></svg></span></span>;}
export function Pressure(){return <div className="pressure-art"><img className="pressure-owner" src="/images/owner-pressure.jpg" width="1536" height="1024" loading="lazy" alt="Business owner at a desk, interrupted by competing tasks."/>{c.pressure.objects.map(([title,note],i)=><div className={`interruption interruption-${i}`} key={i}>{i===1||i===2?<Invoice/>:i===7?<svg className="whatsapp-icon" viewBox="0 0 32 32" aria-label="WhatsApp"><path d="M16 3A12 12 0 0 0 6 22L4 29l7-2A12 12 0 1 0 16 3Z" fill="#386f65"/><path d="M11 9c-4 3 4 13 9 13l2-4-4-2-2 2c-2-1-4-3-4-5l2-1Z" fill="#f4e6ce"/></svg>:<Tile kind={[3,1,1,0,2,0,0][i]}/>}<div><strong>{title}</strong><small>{note}</small></div><i/></div>)}</div>;}
export function Transformation(){return <div className="transformation-art"><img src="/images/transformation-source.jpg" width="1672" height="941" loading="lazy" alt="Layered manual papers converge through a human decision into an orderly sequence of tasks, dates, messages and completion."/><Route viewBox="0 0 1672 941" d="M430 280 C650 280 690 550 1005 550 M410 480 C660 480 770 550 1005 550 M390 730 C720 730 720 550 1005 550"/><div className="human-caption">Human judgment stays at the center.</div></div>;}
