'use client';
import {useEffect} from 'react';
export default function Motion(){useEffect(()=>{
 const media=matchMedia('(min-width: 801px) and (prefers-reduced-motion: no-preference)');const visible=new Set<HTMLElement>();let frame=0;const scenes=Array.from(document.querySelectorAll<HTMLElement>('[data-motion]'));const rail=document.querySelector<HTMLElement>('.continuity-thread');
 const anim=matchMedia('(prefers-reduced-motion: no-preference)');const mobile=matchMedia('(max-width: 800px)');const fits=Array.from(document.querySelectorAll<SVGSVGElement>('[data-mfit]')).map(el=>[el,el.getAttribute('preserveAspectRatio')||'xMidYMid meet',el.dataset.mfit||''] as const);
 function update(){frame=0;const enabled=media.matches;document.documentElement.classList.toggle('motion-ready',enabled);document.documentElement.classList.toggle('anim-ready',anim.matches);fits.forEach(([el,desk,mob])=>el.setAttribute('preserveAspectRatio',mobile.matches?mob:desk));visible.forEach(el=>{const r=el.getBoundingClientRect();const raw=enabled?Math.max(0,Math.min(1,(72-r.top)/Math.max(1,r.height-(innerHeight-72)))):1;const ink=Math.max(0,Math.min(1,(raw-.1)/.75));el.style.setProperty('--progress',String(raw));el.style.setProperty('--ink',String(ink));el.style.setProperty('--travel',`${(1-ink)*12}px`);if(r.top<=innerHeight*.4&&r.bottom>innerHeight*.4){document.querySelectorAll('nav a').forEach(a=>{if(a.getAttribute('href')===`#${el.id}`)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}});const total=document.documentElement.scrollHeight-innerHeight;rail?.style.setProperty('--page-progress',String(total>0?scrollY/total:0));}
 function schedule(){if(!frame)frame=requestAnimationFrame(update);}const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{const el=entry.target as HTMLElement;if(entry.isIntersecting){visible.add(el);if(!mobile.matches||!el.querySelector('[data-trigger]'))el.classList.add('seen');el.classList.add('in-view');}else{visible.delete(el);el.classList.remove('in-view');}});schedule();});
 // Phones: a scene with a data-trigger element (its artwork) starts its animation only once that artwork sits in the middle band of the screen.
 const trigger=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){(entry.target as HTMLElement).closest('[data-motion]')?.classList.add('seen');trigger.unobserve(entry.target);}});schedule();},{rootMargin:'-12% 0px -28% 0px'});if(mobile.matches)document.querySelectorAll('[data-trigger]').forEach(el=>trigger.observe(el));scenes.forEach(el=>observer.observe(el));window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);media.addEventListener('change',schedule);schedule();return()=>{observer.disconnect();trigger.disconnect();window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule);media.removeEventListener('change',schedule);cancelAnimationFrame(frame);document.documentElement.classList.remove('motion-ready');document.documentElement.classList.remove('anim-ready');};
 },[]);return <div className="continuity-thread" aria-hidden="true"><span/><i/></div>;}
