/* eslint-disable @next/next/no-img-element -- Local artwork with explicit dimensions. */
import c from './content.json';
import Icon from './components/Icon';
import type {CSSProperties} from 'react';
import './desktop-approved.css';
import {Workflow,Opportunity,Pressure,Transformation,Route} from './components/Artwork';
import Scene from './components/Scene';
import Process from './components/Process';
import Contact from './components/Contact';
import Motion from './components/Motion';
function CTA(){return <a className="button" href="#contact">{c.cta}<Icon/></a>;}
export default function Home(){return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><a className="brand" href="#top" aria-label="TMAutomations home"><span>TM</span>Automations</a><nav aria-label="Primary navigation">{c.nav.map(item=><a key={item.id} href={`#${item.id}`}>{item.label}</a>)}</nav></header><main id="main"><Motion/>
 <Scene id="top" name="hero" titleId="hero-title" next="pressure"><div className="scene-copy"><h1 id="hero-title">There’s another<br/>way this day<br/>could go.</h1><p>{c.hero.body}</p></div><div className="hero-art"><img src="/images/hero-d.png" width="1733" height="907" alt="Hands connecting business tasks with teal thread; a notepad lists review cash flow, approve proposal, and follow up with client."/><svg className="hero-threads" viewBox="0 0 1733 907" aria-hidden="true"><path d="M1025 327Q1046 389 1038 434"/><path d="M844 476L972 494"/><path d="M1199 375Q1130 400 1106 447"/><path d="M1042 572Q1098 596 1190 598"/><path d="M1042 573C1085 650 980 640 1040 694S990 736 1025 780S900 807 880 848"/></svg></div></Scene>
 <Scene id="pressure" name="pressure" titleId="pressure-title" next="possibility"><div className="scene-copy"><h2 id="pressure-title"><span>You know this day.</span><span>You live it.</span></h2><p>{c.pressure.body}</p><p className="pressure-consequence">{c.pressure.consequence}</p></div><Pressure/></Scene>
 <Scene id="possibility" name="possibility" titleId="possibility-title" length={230} next="opportunity"><div className="scene-copy"><h2 id="possibility-title">{c.possibility.title}</h2><p>{c.possibility.body}</p></div><div className="possibility-art"><div className="drafting-fragments" aria-hidden="true"/><Workflow labels/></div></Scene>
 <Scene id="opportunity" name="opportunity" titleId="opportunity-title" length={300} next="approach"><div className="scene-copy"><h2 id="opportunity-title">{c.opportunity.title}</h2><p>{c.opportunity.body}</p></div><Opportunity/></Scene>
 <Scene id="approach" name="approach" titleId="approach-title" length={180} next="process"><div className="scene-copy"><h2 id="approach-title">{c.approach.title}</h2><p>{c.approach.accountability}</p></div><div className="collaboration-image"><img src="/images/collaboration.jpg" width="1672" height="941" alt={c.approach.alt} loading="lazy"/><Route className="approach-thread" viewBox="0 0 1672 941" d="M1126 665 Q1100 675 1040 687 L1097 706 Q1154 715 1140 748 L1030 743 Q974 760 884 789 L784 750 Q779 727 857 722 L1020 743 Q1080 783 1160 779 L1204 807 L1080 855 Q985 875 945 839"/></div></Scene>
 <Process/>
 <Scene id="transformation" name="signature" titleId="signature-title" length={340} next="work"><div className="scene-copy"><h2 id="signature-title">{c.transformation.title}</h2><p>{c.transformation.body}</p></div><Transformation/></Scene>
 <Scene id="work" name="work" titleId="work-title" next="payoff"><div className="scene-copy"><h2 id="work-title"><span>See what moved.</span><span>Know what needs attention.</span></h2><p>Less chasing.<br/>Clearer decisions.<br/>Greater control.</p></div><div className="work-ledger"><div className="ledger-columns">{c.work.states.map((state,i)=><article className={`ledger-column state-${i}`} key={state.title}><h3>{state.title}</h3><ul>{state.tasks.map((task,j)=><li className="ledger-task" key={task} style={{'--task-delay':`${1.1+([0,5,12][i]+j)*.48}s`} as CSSProperties}><svg className="task-box" viewBox="0 0 26 26" aria-hidden="true"><path d="M3 3L23 2L24 23L2 24Z"/>{i!==2&&<path className="task-check" pathLength="1" d="m6 13 5 5L21 7"/>}</svg><span>{task}</span></li>)}</ul><p>{state.note}</p></article>)}</div></div></Scene>
 <Scene id="payoff" name="payoff" titleId="payoff-title" next="contact"><div className="scene-copy"><h2 id="payoff-title">{c.payoff.title}</h2><p>{c.payoff.body}</p><p className="owner-benefit">Clarity on the work.<br/>Control of the decisions.<br/>Time to leave on time.</p><div className="closing"><p>Tell us how your business works today.<br/>We’ll start there.</p><CTA/></div></div><div className="payoff-image"><img src="/images/payoff.jpg" width="1672" height="941" loading="lazy" alt={c.payoff.alt}/><Route d="M150 500 H500 C650 500 680 300 850 300"/></div></Scene>
 <section id="contact" className="contact scene" data-motion aria-labelledby="contact-title"><div className="shell contact-layout"><div><h2 id="contact-title">{c.contact.title}</h2><p>{c.contact.body}</p><address><strong>{c.brand}</strong><a href={c.contact.phoneHref}>{c.contact.phone}</a><a href={c.contact.websiteHref}>{c.contact.website}</a><a href={`mailto:${c.contact.email}`}>{c.contact.email}</a></address></div><Contact/></div></section>
 </main><footer className="shell"><a className="brand" href="#top"><span>TM</span>Automations</a><p>{c.footer}</p></footer></>;}
