/* eslint-disable @next/next/no-img-element -- Local artwork with explicit dimensions. */
import c from './content.json';
import Icon from './components/Icon';
import type {CSSProperties} from 'react';
import './desktop-approved.css';
import './mobile.css';
import {Workflow,Opportunity,Pressure,Transformation,Route} from './components/Artwork';
import Scene from './components/Scene';
import Process from './components/Process';
import Contact from './components/Contact';
import Motion from './components/Motion';
import ContactPopup from './components/ContactPopup';
function CTA(){return <a className="button" href="#contact">{c.cta}<Icon/></a>;}
export default function Home(){return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><a className="brand" href="#top" aria-label="TMAutomations home"><span>TM</span>Automations</a><nav aria-label="Primary navigation">{c.nav.map(item=><a key={item.id} href={`#${item.id}`}>{item.label}</a>)}</nav></header><main id="main"><Motion/>
 <Scene id="top" name="hero" titleId="hero-title" next="pressure"><div className="scene-copy"><h1 id="hero-title">There’s another<br/>way this day<br/>could go.</h1><p>{c.hero.body}</p></div><div className="hero-art"><img src="/images/hero-d.jpg" width="1733" height="907" alt="Hands connecting business tasks with teal thread; a notepad lists review cash flow, approve proposal, and follow up with client."/><svg className="hero-threads" viewBox="0 0 1733 907" preserveAspectRatio="xMidYMid meet" data-mfit="xMidYMid slice" aria-hidden="true"><path d="M1025 327Q1046 389 1038 434"/><path d="M844 476L972 494"/><path d="M1199 375Q1130 400 1106 447"/><path d="M1042 572Q1098 596 1190 598"/><path d="M1042 573C1085 650 980 640 1040 694S990 736 1025 780S900 807 880 848"/></svg></div></Scene>
 <Scene id="pressure" name="pressure" titleId="pressure-title" next="possibility"><div className="scene-copy"><h2 id="pressure-title"><span>You know this day.</span><span>You live it.</span></h2><p>{c.pressure.body}</p><p className="pressure-consequence">{c.pressure.consequence}</p></div><Pressure/></Scene>
 <Scene id="possibility" name="possibility" titleId="possibility-title" length={160} next="opportunity"><div className="scene-copy"><h2 id="possibility-title">{c.possibility.title}</h2><p>{c.possibility.body}</p></div><div className="possibility-art"><div className="drafting-fragments" aria-hidden="true"/><Workflow labels/></div></Scene>
 <Scene id="opportunity" name="opportunity" titleId="opportunity-title" length={200} next="approach"><div className="scene-copy"><h2 id="opportunity-title">{c.opportunity.title}</h2><p>{c.opportunity.body}</p></div><Opportunity/></Scene>
 <Scene id="approach" name="approach" titleId="approach-title" length={140} next="process"><div className="scene-copy"><h2 id="approach-title">{c.approach.title}</h2><p>{c.approach.accountability}</p></div><div className="collaboration-image"><img src="/images/collaboration.jpg" width="1672" height="941" alt={c.approach.alt} loading="lazy"/><Route className="approach-thread" viewBox="0 0 1672 941" mfit="xMidYMax slice" d="M1125 662 C1121 670 1118 694 1100 707 C1083 720 1060 739 1020 742 C980 745 896 723 858 724 C820 725 814 738 792 748 C770 758 712 778 728 784 C744 790 847 777 886 786 C926 795 923 842 965 836 C1007 830 1102 755 1140 750 C1178 745 1183 795 1192 804"/></div></Scene>
 <Process/>
 <Scene id="transformation" name="signature" titleId="signature-title" length={120} next="work"><div className="scene-copy"><h2 id="signature-title">{c.transformation.title}</h2><p>{c.transformation.body}</p></div><Transformation/></Scene>
 <Scene id="work" name="work" titleId="work-title" next="payoff"><div className="scene-copy"><h2 id="work-title"><span>See what moved.</span><span>Know what needs attention.</span></h2><p>Less chasing.<br/>Clearer decisions.<br/>Greater control.</p></div><div className="work-ledger dashboard"><header className="dash-summary" aria-label="Summary">{c.work.states.map((state,i)=><div className={`dash-count state-${i}`} key={state.title}><span className="count"><svg viewBox="0 0 60 60" aria-hidden="true"><path pathLength="1" d="M12 30c1-11 10-18 20-17s18 9 17 19-10 17-20 16-18-8-17-18"/></svg>{state.tasks.length}</span><span>{state.title}</span></div>)}</header><div className="ledger-columns">{c.work.states.map((state,i)=><article className={`ledger-column state-${i}`} key={state.title}><h3>{state.title}</h3><ul>{state.tasks.map((task,j)=><li className="ledger-task" key={task} style={{'--task-delay':`${1.1+([0,5,12][i]+j)*.48}s`} as CSSProperties}><span className="task-box" aria-hidden="true"><svg viewBox="0 0 26 26"><path d="M3 3L23 2L24 23L2 24Z"/></svg>{i!==2&&<i className={`task-check check-${j%3}`}/>}</span><span>{task}</span></li>)}</ul><p>{state.note}</p></article>)}</div></div></Scene>
 <Scene id="payoff" name="payoff" titleId="payoff-title" next="contact"><div className="scene-copy"><h2 id="payoff-title">{c.payoff.title}</h2><p>{c.payoff.body}</p><p className="owner-benefit">Clarity on the work.<br/>Control of the decisions.<br/>Time to leave on time.</p><div className="closing"><p>Tell us how your business works today.<br/>We’ll start there.</p><CTA/></div></div><div className="payoff-image"><img src="/images/payoff.jpg" width="1672" height="941" loading="lazy" alt={c.payoff.alt}/><Route className="payoff-thread" viewBox="0 0 1672 941" fit="xMaxYMid slice" d="M1215 758 C1160 790 1090 800 1040 815 C990 830 930 830 900 805 C870 780 890 745 940 745 C1030 745 1150 725 1300 715 C1390 710 1400 650 1420 560 C1440 470 1455 410 1478 360 C1490 335 1505 320 1520 312"/></div></Scene>
 <section id="contact" className="contact scene" data-motion aria-labelledby="contact-title"><ContactPopup/><button type="button" className="contact-close" aria-label="Close"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5l14 14M19 5L5 19"/></svg></button><div className="shell contact-layout"><div><h2 id="contact-title">{c.contact.title}</h2><p>{c.contact.body}</p><address><strong>{c.brand}</strong><a href={c.contact.phoneHref}>{c.contact.phone}</a><a href={c.contact.websiteHref}>{c.contact.website}</a></address></div><Contact/></div></section>
 </main><footer className="shell"><a className="brand" href="#top"><span>TM</span>Automations</a><p>{c.footer}</p></footer></>;}
